routes:
  /: home
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /cuisine/:
    permalink: /cuisine/{slug}/
    filter: primary_tag:cuisine
  /fictions/:
    permalink: /fictions/{slug}/
    filter: primary_tag:fictions
